baseURL = "http://blog.gripdev.xyz"
languageCode = "en"
title = "gripdev.xyz"
theme = "hugo-blog-awesome"

[taxonomies]
category = "category"
tag = "tag"

[params]
description = "Code, Apps and Thoughts @lawrencegripper"
defaultTheme = "hugo-blog-awesome"
disableThemeToggle = true
showShareButtons = true
showReadingTime = true
showToc = false
showBreadCrumbs = true
showCodeCopyButtons = true
comments = true
# hideFooter = true
mainSections = ['posts']


[params.author]
avatar = "lawrencegripper.jpeg" # put the file in assets folder; also ensure that image has same height and width
# Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
intro = "Code and Thoughts"
name = "Lawrence Gripper"
description = "I’m Lawrence Gripper, a software engineer working at GitHub"

# [params.assets]
# disableHLJS = true

[params.assets]
favicon = "/favicon.ico"
disableHLJS = true

[menu]
[[menu.main]]
  # The page reference (pageRef) is useful for menu highlighting
  # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
  pageRef="/"
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  pageRef="posts"
  name = 'Posts'
  url = '/posts/'
  weight = 20
[[menu.main]]
  pageRef="tags"
  name = 'Tags'
  url = '/tag/'
  weight = 20
[[menu.main]]
  pageRef="about"
  name = 'About'
  url = '/about/'
  weight = 30

# [markup.highlight]
# codeFences = true
# guessSyntax = true
# style = "monokai"

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[outputFormats.RSS]
mediaType = "application/rss+xml"
baseName = "feed"

